### PR TITLE
Loader

### PR DESCRIPTION
**Pull request by CJ-Wright**
Write the DB loader for temperature samples, may need some more conditionals to handle the sample changer

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@ericdill thoughts? I wouldn't look at the loader itself just the dry run, which I think gets most of the data parsed.

**Comment by CJ-Wright** [comment]
also @DrBoreX thoughts?

**Comment by ericdill** [comment]
First thought is, "What exactly would you like me to look at :grinning: "

**Comment by CJ-Wright** [comment]
I think mainly the`loader_dry_run` in `side_loader`.
I essentially tried to mimic the loader you showed me but without actually loading the files into the DB and with all the logic kinda sorted out.

**Comment by ericdill** [comment]
Wait why not just try to load the files into the DB? It's easy enough to just drop the database if it is wrong

**Comment by CJ-Wright** [comment]
I haven't setup all the DBs yet.
But fair point. I'll set everything up. Unless you have neat install script/conda for a dev version of the DB stack.

**Comment by ericdill** [comment]
oh. I don't know that I will be able to just look at the code and determine if the code is going to work or not.  The DBs should be pretty easy to set up. Just install mongodb on your local computer and try it out

**Comment by CJ-Wright** [comment]
k, thank you.

**Comment by CJ-Wright** [comment]
This is pending some discussion at databroker about how/where to save calibration and background data.

**Pull request merged**
